<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz: {{ $quiz->topic }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 20px;
        }

        .question {
            margin-bottom: 20px;
        }

        .question p {
            font-size: 14px;
            line-height: 1.6;
        }

        .options {
            margin-left: 20px;
            font-size: 14px;
        }

        .options label {
            display: block;
            margin-bottom: 6px;
        }

        .page-break {
            page-break-before: always;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <h1>Quiz: {{ $quiz->topic }}</h1>

    <div>
        @foreach($questions as $idx => $q)
            <div class="question">
                <p><strong>{{ $idx + 1 }}. {{ $q['soal'] }}</strong></p>

                <div class="options">
                    @foreach($q['opsi'] as $i => $opt)
                        <label><strong>{{ $i }}.</strong> {{ $opt }}</label>
                    @endforeach
                </div>
            </div>

            <!-- Page Break for each question (optional) -->
            @if (($idx + 1) % 5 == 0)
                <div class="page-break"></div>
            @endif
        @endforeach
    </div>

    <div class="footer">
        <p>Generated by Quiz Application</p>
    </div>
</body>
</html>
